-- Ejecuta este archivo en Supabase > SQL Editor.
-- Esta versión deja la agenda pública en modo lectura y recibe solicitudes
-- anónimas. El personal de soporte debe iniciar sesión en Supabase Auth.

create table if not exists public.reservas (
  id bigint generated by default as identity primary key,
  fecha date not null,
  bloque smallint not null check (bloque between 1 and 9),
  profesor text not null check (char_length(trim(profesor)) >= 3),
  curso text not null check (curso ~ '^[0-9]{1,2}[A-Z]$'),
  created_at timestamptz not null default now()
);

create unique index if not exists reservas_fecha_bloque_unica
  on public.reservas (fecha, bloque);

create table if not exists public.solicitudes_reserva (
  id uuid primary key default gen_random_uuid(),
  fecha date not null,
  bloque smallint not null check (bloque between 1 and 9),
  profesor text not null check (char_length(trim(profesor)) >= 3),
  correo text not null check (correo ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  curso text not null check (curso ~ '^[0-9]{1,2}[A-Z]$'),
  comentario text not null default '',
  estado text not null default 'pendiente' check (estado in ('pendiente', 'aprobada', 'rechazada')),
  motivo_rechazo text,
  revisada_en timestamptz,
  revisada_por uuid references auth.users(id),
  correo_estado text not null default 'pendiente' check (correo_estado in ('pendiente', 'enviado', 'error')),
  correo_error text,
  correo_enviado_en timestamptz,
  created_at timestamptz not null default now()
);

alter table public.reservas enable row level security;
alter table public.solicitudes_reserva enable row level security;

drop policy if exists "reservas_lectura_publica" on public.reservas;
create policy "reservas_lectura_publica" on public.reservas
  for select to anon, authenticated using (true);
-- La agenda pública expone sólo el bloque y el curso, nunca el nombre docente.
revoke select on table public.reservas from anon;
grant select (id, fecha, bloque, curso, created_at) on table public.reservas to anon;
drop policy if exists "reservas_insercion_publica" on public.reservas;
drop policy if exists "reservas_borrado_publico" on public.reservas;

drop policy if exists "solicitudes_creacion_publica" on public.solicitudes_reserva;
create policy "solicitudes_creacion_publica" on public.solicitudes_reserva
  for insert to anon, authenticated
  with check (estado = 'pendiente' and revisada_por is null and revisada_en is null);
drop policy if exists "solicitudes_soporte_lectura" on public.solicitudes_reserva;
create policy "solicitudes_soporte_lectura" on public.solicitudes_reserva
  for select to authenticated using (public.suite_is_support());

-- Sólo usuarios autenticados (soporte) pueden aprobar. La función evita la
-- doble reserva aunque dos personas revisen una solicitud al mismo tiempo.
create or replace function public.aprobar_solicitud_reserva(solicitud_id uuid)
returns public.solicitudes_reserva
language plpgsql security definer set search_path = public
as $$
declare solicitud public.solicitudes_reserva;
begin
  if auth.uid() is null or not public.suite_is_support() then raise exception 'No autorizado'; end if;
  select * into solicitud from public.solicitudes_reserva where id = solicitud_id for update;
  if not found then raise exception 'Solicitud no encontrada'; end if;
  if solicitud.estado <> 'pendiente' then raise exception 'Esta solicitud ya fue revisada'; end if;
  insert into public.reservas (fecha, bloque, profesor, curso)
    values (solicitud.fecha, solicitud.bloque, solicitud.profesor, solicitud.curso);
  update public.solicitudes_reserva set estado = 'aprobada', revisada_en = now(), revisada_por = auth.uid()
    where id = solicitud_id returning * into solicitud;
  return solicitud;
end;
$$;

-- Aprueba varias solicitudes en una sola transacción. Si falta una solicitud,
-- ya fue revisada o alguno de los bloques está ocupado, no se aprueba ninguna.
create or replace function public.aprobar_solicitudes_reserva(solicitud_ids uuid[])
returns setof public.solicitudes_reserva
language plpgsql security definer set search_path = public
as $$
declare
  cantidad_solicitada integer;
  cantidad_pendiente integer;
begin
  if auth.uid() is null or not public.suite_is_support() then raise exception 'No autorizado'; end if;

  select count(distinct id)
    into cantidad_solicitada
    from unnest(coalesce(solicitud_ids, array[]::uuid[])) as ids(id);

  if cantidad_solicitada = 0 then
    raise exception 'Selecciona al menos una solicitud';
  end if;

  -- Bloquea todas las solicitudes antes de validar o escribir en la agenda.
  perform 1
    from public.solicitudes_reserva
    where id = any(solicitud_ids)
    for update;

  select count(*)
    into cantidad_pendiente
    from public.solicitudes_reserva
    where id = any(solicitud_ids) and estado = 'pendiente';

  if cantidad_pendiente <> cantidad_solicitada then
    raise exception 'Una o más solicitudes no existen o ya fueron revisadas';
  end if;

  insert into public.reservas (fecha, bloque, profesor, curso)
    select fecha, bloque, profesor, curso
    from public.solicitudes_reserva
    where id = any(solicitud_ids);

  return query
    update public.solicitudes_reserva
      set estado = 'aprobada', revisada_en = now(), revisada_por = auth.uid()
      where id = any(solicitud_ids)
      returning *;
end;
$$;

create or replace function public.rechazar_solicitud_reserva(solicitud_id uuid, motivo text default null)
returns public.solicitudes_reserva
language plpgsql security definer set search_path = public
as $$
declare solicitud public.solicitudes_reserva;
begin
  if auth.uid() is null or not public.suite_is_support() then raise exception 'No autorizado'; end if;
  update public.solicitudes_reserva set estado = 'rechazada', motivo_rechazo = nullif(trim(motivo), ''),
    revisada_en = now(), revisada_por = auth.uid()
    where id = solicitud_id and estado = 'pendiente' returning * into solicitud;
  if not found then raise exception 'La solicitud no existe o ya fue revisada'; end if;
  return solicitud;
end;
$$;

revoke all on function public.aprobar_solicitud_reserva(uuid) from public;
revoke all on function public.aprobar_solicitudes_reserva(uuid[]) from public;
revoke all on function public.rechazar_solicitud_reserva(uuid, text) from public;
grant execute on function public.aprobar_solicitud_reserva(uuid) to authenticated;
grant execute on function public.aprobar_solicitudes_reserva(uuid[]) to authenticated;
grant execute on function public.rechazar_solicitud_reserva(uuid, text) to authenticated;
