spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/centro_ti}
spring.datasource.username=${DATABASE_USERNAME:centro_ti}
spring.datasource.password=${DATABASE_PASSWORD:centro_ti}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
